// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	UserName string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token string `json:"token"`
}

type GetUserRequest struct {
	ID int `form:"id"`
}

type GetUserResponse struct {
	ID         int    `json:"id"`
	RoleID     int    `json:"role_id"`
	RoleName   string `json:"role_name"`
	TeamID     int    `json:"team_id"`
	TeamName   string `json:"team_name"`
	Name       string `json:"name"`
	Phone      string `json:"phone"`
	Avatar     string `json:"avatar"`
	Email      string `json:"email"`
	Status     bool   `json:"status"`
	Operator   string `json:"operator"`
	OperatorID int    `json:"operator_id"`
	CreatedAt  int64  `json:"created_at"`
	UpdatedAt  int64  `json:"updated_at"`
}

type GetUserPageRequest struct {
	TeamID     int    `json:"team_id,optional"`
	RoleID     int    `json:"role_id,optional"`
	Name       string `json:"name,optional"`
	OperatorID int    `json:"operator_id,optional"`
	Status     bool   `json:"status,optional"`
}

type GetUserPageResponse struct {
	List []GetUserResponse `json:"list"`
}

type AddUserRequest struct {
	RoleID int    `json:"role_id"`
	TeamID int    `json:"team_id"`
	Name   string `json:"name"`
	Phone  string `json:"phone"`
	Email  string `json:"email"`
	Status bool   `json:"status"`
}

type UpdateUserRequest struct {
	ID     int    `json:"id"`
	RoleID int    `json:"role_id"`
	TeamID int    `json:"team_id"`
	Name   string `json:"name"`
	Phone  string `json:"phone"`
	Avatar string `json:"avatar"`
	Email  string `json:"email"`
	Status bool   `json:"status"`
}

type DeleteUserRequest struct {
	ID int `json:"id"`
}

type GetTeamResponse struct {
	ID          int               `json:"id"`
	Name        string            `json:"name"`
	Avatar      string            `json:"avatar"`
	Description string            `json:"description"`
	ParentID    int               `json:"parent_id"`
	Children    []GetTeamResponse `json:"children"`
	Operator    string            `json:"operator"`
	OperatorID  int               `json:"operator_id"`
	CreatedAt   int64             `json:"created_at"`
	UpdatedAt   int64             `json:"updated_at"`
}

type AddTeamRequest struct {
	Name        string `json:"name"`
	Avatar      string `json:"avatar,optional"`
	Description string `json:"description,optional"`
	ParentID    int    `json:"parent_id"`
}

type UpdateTeamRequest struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Avatar      string `json:"avatar,optional"`
	Description string `json:"description,optional"`
	ParentID    int    `json:"parent_id"`
}

type DeleteTeamRequest struct {
	ID int `json:"id"`
}

type Role struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	KeyWord     string `json:"key_word"`
	Status      bool   `json:"status"`
	Weight      int    `json:"weight"`
	Description string `json:"description"`
	DataScope   string `json:"data_scope"`
	Operator    string `json:"operator"`
	OperatorID  int    `json:"operator_id"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

type GetRoleRequest struct {
	Name       string `json:"name"`
	KeyWord    string `json:"key_word"`
	Status     *bool  `json:"status"`
	OperatorID int    `json:"operator_id"`
}

type GetRoleResponse struct {
	List []Role `json:"list"`
}

type AddRoleRequest struct {
	Name        string `json:"name"`
	KeyWord     string `json:"key_word"`
	Status      bool   `json:"status,optional"`
	Weight      int    `json:"weight,optional,default=0"`
	Description string `json:"description,optional"`
	DataScope   string `json:"data_scope"`
}

type UpdateRoleRequest struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	KeyWord     string `json:"key_word"`
	Status      bool   `json:"status,optional"`
	Weight      int    `json:"weight,optional,default=0"`
	Description string `json:"description,optional"`
	DataScope   string `json:"data_scope"`
}

type DeleteRoleRequest struct {
	ID int `json:"id"`
}
