// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"devops/configrue/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/check_health",
				Handler: CheckHealthHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/environment/list",
				Handler: GetEnvironmentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/environment/add",
				Handler: AddEnvironmentHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/environment/info",
				Handler: UpdateEnvironmentHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/environment/info",
				Handler: DeleteEnvironmentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/service/list",
				Handler: GetServiceHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/service/add",
				Handler: AddServiceHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/service/info",
				Handler: UpdateServiceHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/service/info",
				Handler: DeleteServiceHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/configrue/list",
				Handler: GetConfigrueHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/configrue/add",
				Handler: AddConfigrueHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/configrue/info",
				Handler: UpdateConfigrueHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/configrue/info",
				Handler: DeleteConfigrueHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/configrue_log/list",
				Handler: GetConfigrueLogHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
