// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"devops/configrue/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/check_health",
				Handler: CheckHealthHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/environment/list",
				Handler: GetEnvironmentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/environment/info",
				Handler: AddEnvironmentHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/environment/info",
				Handler: UpdateEnvironmentHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/environment/info",
				Handler: DeleteEnvironmentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/service/list",
				Handler: GetServiceHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/service/info",
				Handler: AddServiceHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/service/info",
				Handler: UpdateServiceHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/service/info",
				Handler: DeleteServiceHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/configure/info",
				Handler: GetConfigureHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/configure/list",
				Handler: ListConfigureHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/configure/info",
				Handler: AddConfigureHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/configure/info",
				Handler: UpdateConfigureHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/configure/info",
				Handler: DeleteConfigureHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/configure_log/list",
				Handler: GetConfigureLogHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/configure_field/page",
				Handler: PageConfigureFieldHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/configure_field/info",
				Handler: AddConfigureFieldHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/configure_field/info",
				Handler: UpdateConfigureFieldHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/configure_field/info",
				Handler: DeleteConfigureFieldHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/service_field/page",
				Handler: PageServiceFieldHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/service_field/info",
				Handler: AddServiceFieldHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/service_field/info",
				Handler: UpdateServiceFieldHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/service_field/info",
				Handler: DeleteServiceFieldHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/cms"),
	)
}
