Name: user-api
Host: 0.0.0.0
Port: 8888
Auth:
  AccessSecret: "123451116"
  AccessExpire: 7200
  
Mysql:
  DSN: "root:root@tcp(127.0.0.1:3306)/lime_video?charset=utf8mb4&parseTime=True&loc=Local"
  Level: 4 #1-4
  ConnMaxLifetime: 500
  MaxOpenConn: 20
  MaxIdleConn: 10
  SlowThreshold: 1

Redis:
  Host: "127.0.0.1:6379"
  Pass: ""

Rsa:
  PublicKey: "-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCi8+NXa27wtcVviKOCYVltuohv
qRSwWXJ8gReSqH3C0avjCaoXGznpxCXcywiupLt/EuFYd6gqYQ0jRr/qVz5qZXnE
3r4VO7pdLT3GcgCfFvES/1o6WQuCQC0sq1AbZj8vF2goKAmGlSahMDM4uqnTbIsB
Z9XtP7x10asuyvnfYwIDAQAB
-----END PUBLIC KEY-----"
  PrivateKey: "-----BEGIN RSA PRIVATE KEY-----
MIICXQIBAAKBgQCi8+NXa27wtcVviKOCYVltuohvqRSwWXJ8gReSqH3C0avjCaoX
GznpxCXcywiupLt/EuFYd6gqYQ0jRr/qVz5qZXnE3r4VO7pdLT3GcgCfFvES/1o6
WQuCQC0sq1AbZj8vF2goKAmGlSahMDM4uqnTbIsBZ9XtP7x10asuyvnfYwIDAQAB
AoGAWgS5FlX3F2qTAyZMjX4R1Rgyvtx83V7MbBM0XoRN1Q3XErkICXO07nq5H9vZ
lADUw0I+0oxnjeHHTDGNW3uOsn5iDgR+A+j5IXujy1LBmDakM9JxaQFJRkDj37hD
D+L5RWDolVTcqMu2WD00SPnoLgpHd25k4OmpkdCG2zdf54ECQQDP4bxnhjVmh5N/
yuOsV6obtlYbopPfVRPDpo2z+bwpyHhIfF7DtE5n6tHKZBvK3bnIzUUAZgHo2Gf+
EhRh2tBRAkEAyKvUQ24B5OOEqKGlmoxlsS21r8dokhPURA49Pk+cbcE9ieTQHQOx
V+unNYY1lcK1zrGz/ZE+Ma36dyHjIKnbcwJAAXjHrLP2jNNI6A63rfCw86FG2ss7
4Mjpauky96M9Ac65i0nWIeyU4Yd4FMbAq58GQbWyV15hhRSDJ/lYy5iRAQJBAMaz
zqVOQrXgzDUmixKzvuZoeqWp8NPkqqUQ7HfM4PqVBFiMp75zL6H9iD6pvFmkyd33
fGCy90C+I2rftUVcrB0CQQCCID/zJIU5X7ZrPZQmIhdqG1XBlouMMbeqEaoVutoZ
eGBf/m3+nrkf3c0E/jYAb9GaaoRjbYfiFfw4lWKsjJ+N
-----END RSA PRIVATE KEY-----"