Name: configure-api
Host: 0.0.0.0
Port: 8887

Mysql:
  DSN: "root:root@tcp(127.0.0.1:3306)/devops?charset=utf8mb4&parseTime=True&loc=Local"
  Level: 4 #1-4
  ConnMaxLifetime: 500
  MaxOpenConn: 20
  MaxIdleConn: 10
  SlowThreshold: 1

Redis:
  Host: "127.0.0.1:6379"
  Pass: ""

#WxAccount:
#  AppId: "wxb81741cb4e7b415b"
#  Secret: "4ced1b915d74d2e08c1dccd2bcd8c78d"


