// Code generated by goctl. DO NOT EDIT.
package types

type Environment struct {
	ID          int64  `json:"id"`
	Keyword     string `json:"keyword"`
	Name        string `json:"name"`
	Config      string `json:"config"`
	Prefix      string `json:"prefix"`
	Description string `json:"description"`
	Operator    string `json:"operator"`
	OperatorID  int64  `json:"operator_id"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

type GetEnvironmentResponse struct {
	List []Environment `json:"list"`
}

type AddEnvironmentRequest struct {
	Name        string `json:"name"`
	Config      string `json:"config"`
	Prefix      string `json:"prefix"`
	Description string `json:"description"`
}

type UpdateEnvironmentRequest struct {
	ID          int64  `json:"id"`
	Keyword     string `json:"keyword"`
	Name        string `json:"name"`
	Config      string `json:"config"`
	Prefix      string `json:"prefix"`
	Description string `json:"description"`
}

type DeleteEnvironmentRequest struct {
	ID int64 `json:"id"`
}

type Service struct {
	ID          int64  `json:"id"`
	Keyword     string `json:"keyword"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Operator    string `json:"operator"`
	OperatorID  int64  `json:"operator_id"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

type GetServiceRequest struct {
	Page    int64  `json:"page"`
	Count   int64  `json:"count"`
	Keyword string `json:"keyword"`
}

type GetServiceResponse struct {
	List []Service `json:"list"`
}

type AddServiceRequest struct {
	Keyword     string `json:"keyword"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type UpdateServiceRequest struct {
	ID          int64  `json:"id"`
	Keyword     string `json:"keyword"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type DeleteServiceRequest struct {
	ID int64 `json:"id"`
}

type Configure struct {
	ID         int64  `json:"id"`
	ServiceId  string `json:"service_id"`
	Template   string `json:"template"`
	Version    string `json:"version"`
	IsUse      bool   `json:"is_use"`
	Operator   string `json:"operator"`
	OperatorID int64  `json:"operator_id"`
	CreatedAt  int64  `json:"created_at"`
	UpdatedAt  int64  `json:"updated_at"`
}

type GetConfigureRequest struct {
	ServiceId string `json:"service_id"`
	Version   string `json:"version,optional"`
	IsUse     *bool  `json:"is_use,optional"`
}

type GetConfigureResponse struct {
	List []Configure `json:"list"`
}

type AddConfigureRequest struct {
	ServiceId string `json:"service_id"`
	Template  string `json:"template"`
	Version   string `json:"version"`
	IsUse     bool   `json:"is_use"`
}

type UpdateConfigureRequest struct {
	ID        int64  `json:"id"`
	ServiceId string `json:"service_id"`
	Template  string `json:"template"`
	IsUse     bool   `json:"is_use,optional"`
}

type DeleteConfigureRequest struct {
	ID int64 `json:"id"`
}

type ConfigureLog struct {
	ID          int64  `json:"id"`
	ServiceName string `json:"service_name"`
	Title       string `json:"title"`
	Content     string `json:"content"`
	Operator    string `json:"operator"`
	OperatorID  int64  `json:"operator_id"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

type GetConfigureLogRequest struct {
	ServiceName string `json:"service_name,optional"`
}

type GetConfigureLogResponse struct {
	List []ConfigureLog `json:"list"`
}
